=== Aryanpachhai803/xml/Practical/staff.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="staff">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="employee" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string"/>
                            <xs:element name="department" type="xs:string"/>
                            <xs:element name="position" type="xs:string"/>
                            <xs:element name="salary" type="xs:decimal"/>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:string" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== Aryanpachhai803/xml/Practical/staff.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE staff System "staff.dtd">
<?xml-stylesheet type="text/xsl" href="staff.xsl"?>

<staff xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="staff.xsd">
    <employee id="E1">
        <name>Alex</name>
        <department>HR</department>
        <position>Manager</position>
        <salary>45000</salary>
    </employee>

    <employee id="E2">
        <name>Rohan</name>
        <department>IT</department>
        <position>Developer</position>
        <salary>85000</salary>
    </employee>
</staff>
